INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (2,'Spider-Man',7.3,782656);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (3,'The Amazing Spider-Man',6.9,628181);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (4,'Spider-Man 2',7.4,622160);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (5,'Spider-Man: Homecoming',7.4,612769);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (6,'Spider-Man 3',6.2,563755);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (7,'The Amazing Spider-Man 2',6.6,474218);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (8,'Spider-Man: No Way Home',8.7,473284);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (9,'Spider-Man: Into the Spider-Verse',8.4,473159);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (10,'Spider-Man: Far from Home',7.4,444812);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (11,'Along Came a Spider',6.4,83433);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (13,'Spider',6.8,38365);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (14,'Kiss of the Spider Woman',7.3,15386);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (15,'Big Ass Spider!',5.3,7217);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (16,'Spider Baby or, the Maddest Story Ever Told',6.8,6813);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (17,'The Spider Woman',7.0,4529);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (18,'The Giant Spider Invasion',3.2,4180);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (19,'Horrors of Spider Island',2.6,3948);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (20, 'Horrors of Spider Island',2.6,3948);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (21,'The Spider',4.5,3018);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (22,'Spider',7.7,2793);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (24,'Earth vs. the Spider',4.3,2162);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (25,'Spider Lilies',6.2,2033);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (26,'Spider in the Web',4.5,1660);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (27,'Spider-Plant Man',6.4,1557);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (28,'Jack Black: Spider-Man',7.5,1537);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (29,'The Red Spider',5.8,1415);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (30,'Spider-Man: Homecoming, NBA Finals: Watch the Game',7.5,1234);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (31,'Spider-Man Strikes Back',5.4,817);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (32,'Spider',6.3,802);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (33,'Spider-Ham: Caught in a Ham',6.2,741);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (35,'The Amazing Adventures of Spider-Man',8.6,721);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (36,'Web of the Spider',5.6,714);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (37,'Spider-Man: The Dragon''s Challenge',5.2,692);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (38,'The Spider Labyrinth',6.5,611);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (39,'The Lost Spider Pit Sequence',7.4,526);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (40,'The Girl and the Spider',6.2,517);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (41,'Eyes of the Spider',6.5,498);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (42,'Spider-Man Title Reveal',7.8,373);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (43,'The Itsy Bitsy Spider',6.1,360);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (44,'The Spider and the Fly',6.8,351);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (46,'Monmon the Water Spider',7.6,351);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (47,'Spider Man: Lost Cause',5.2,346);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (48,'Spider & Rose',6.8,297);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (49,'Spider-Man 2: Another World',7.2,292);
INSERT INTO MOVIE(id,title,average_of_votes,number_of_votes) VALUES (50,'The Spider and the Fly',6.4,287);
